function [initial_state,playtime_white,playtime_black]=init_board(playtime)
initial_state_white=[create_khana('White','Rook',1,1,'Alive');
    create_khana('White','Knight',2,1,'Alive');
    create_khana('White','Bishop',3,1,'Alive');
    create_khana('White','Queen',4,1,'Alive');
    create_khana('White','King',5,1,'Alive');
    create_khana('White','Bishop',6,1,'Alive');
    create_khana('White','Knight',7,1,'Alive');
    create_khana('White','Rook',8,1,'Alive');
    create_khana('White','pawn',1,2,'Alive');
    create_khana('White','pawn',2,2,'Alive');
    create_khana('White','pawn',3,2,'Alive');
    create_khana('White','pawn',4,2,'Alive');
    create_khana('White','pawn',5,2,'Alive');
    create_khana('White','pawn',6,2,'Alive');
    create_khana('White','pawn',7,2,'Alive');
    create_khana('White','pawn',8,2,'Alive')];

initial_state_black=[create_khana('Black','Rook',1,8,'Alive');
    create_khana('Black','Knight',2,8,'Alive');
    create_khana('Black','Bishop',3,8,'Alive');
    create_khana('Black','Queen',4,8,'Alive');
    create_khana('Black','King',5,8,'Alive');
    create_khana('Black','Bishop',6,8,'Alive');
    create_khana('Black','Knight',7,8,'Alive');
    create_khana('Black','Rook',8,8,'Alive');
    create_khana('Black','pawn',1,7,'Alive');
    create_khana('Black','pawn',2,7,'Alive');
    create_khana('Black','pawn',3,7,'Alive');
    create_khana('Black','pawn',4,7,'Alive');
    create_khana('Black','pawn',5,7,'Alive');
    create_khana('Black','pawn',6,7,'Alive');
    create_khana('Black','pawn',7,7,'Alive');
    create_khana('Black','pawn',8,7,'Alive')];

initial_state=[initial_state_white;initial_state_black];
playtime_white=playtime;
playtime_black=playtime;
 end